# **1. 파이토치(Pytorch)**

* 텐서플로우와 함께 머신러닝 딥러닝에서 가장 널리 사용되는 프레임워크
* 초기에는 Torch라는 이르으로 Lua 언어 기반으로 만들어졌으나, 파이썬 기반으로 변경한 것이 파이토치
* 뉴욕대학교와 페이스북(메타)이 공동으로 개발하였고, 현재 가장 대중적이고 사용자가 많은 머신러닝 딥러닝 프레임워크

In [1]:
import torch

print(torch.__version__)

2.3.0+cu121


### 1-1. 스칼라(Scalar)

* 하나의 상수를 의미

In [2]:
var1 = torch.tensor([10])

var1

tensor([10])

In [3]:
type(var1)

torch.Tensor

In [4]:
var2 = torch.tensor([10.5])

var2

tensor([10.5000])

In [5]:
# 두 스칼라의 사칙 연산

print(var1 + var2)
print(var1 - var2)
print(var1 * var2)
print(var1 / var2)

tensor([20.5000])
tensor([-0.5000])
tensor([105.])
tensor([0.9524])


### 1-2. 벡터(vector)

* 상수가 2개 이상 나열된 경우


In [6]:
vec1 = torch.tensor([1, 2, 3])

vec1

tensor([1, 2, 3])

In [7]:
vec2 = torch.tensor([1.4, 5.3, 3.8])

vec2

tensor([1.4000, 5.3000, 3.8000])

In [8]:
print(vec1 + vec2)
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)

tensor([2.4000, 7.3000, 6.8000])
tensor([-0.4000, -3.3000, -0.8000])
tensor([ 1.4000, 10.6000, 11.4000])
tensor([0.7143, 0.3774, 0.7895])


In [9]:
vec3 = torch.tensor([5, 10])

vec3

tensor([ 5, 10])

In [10]:
# vec1 + vec3 :  상수 수가 맞지 않아서 에러 발생

### 1-3. 행열(metrix)

* 2개 이상의 벡터 값을 가지고 만들어지는 행과 열의 개념을 가진 데이터의 나열

In [11]:
mat1 = torch.tensor([[1, 2], [3, 4]])

mat1

tensor([[1, 2],
        [3, 4]])

In [12]:
mat2 = torch.tensor([[7, 8], [9, 10]])

mat2

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
print(mat1 + mat2)
print(mat1 - mat2)
print(mat1 * mat2)
print(mat1 / mat2)

tensor([[ 8, 10],
        [12, 14]])
tensor([[-6, -6],
        [-6, -6]])
tensor([[ 7, 16],
        [27, 40]])
tensor([[0.1429, 0.2500],
        [0.3333, 0.4000]])


### 1-4. 텐서(tensor)

* 다수의 행열이 모이면 텐서
* 배열이나 행열과 매우 유사한 특수 자료구조
* 파이토치는 텐서를 사용하여 모델의 입력과 출력 모델의 매개변수들을 처리

<center><img src='https://miro.medium.com/max/875/1*jRyyMAhS_NZxqyv3EoLCvg.png' width=500></center>

In [14]:
tensor1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

tensor1

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [15]:
tensor2 = torch.tensor([[[9, 10], [10, 11]], [[11, 12], [12, 13]]])

tensor2

tensor([[[ 9, 10],
         [10, 11]],

        [[11, 12],
         [12, 13]]])

In [16]:
print(tensor1 + tensor2)
print(tensor1 - tensor2)
print(tensor1 * tensor2)
print(tensor1 / tensor2)

tensor([[[10, 12],
         [13, 15]],

        [[16, 18],
         [19, 21]]])
tensor([[[-8, -8],
         [-7, -7]],

        [[-6, -6],
         [-5, -5]]])
tensor([[[  9,  20],
         [ 30,  44]],

        [[ 55,  72],
         [ 84, 104]]])
tensor([[[0.1111, 0.2000],
         [0.3000, 0.3636]],

        [[0.4545, 0.5000],
         [0.5833, 0.6154]]])


In [17]:
# 함수를 이용한 사칙 연산

print(torch.add(tensor1, tensor2))
print(torch.subtract(tensor1, tensor2))
print(torch.multiply(tensor1, tensor2))
print(torch.divide(tensor1, tensor2))
print(torch.matmul(tensor1, tensor2))

tensor([[[10, 12],
         [13, 15]],

        [[16, 18],
         [19, 21]]])
tensor([[[-8, -8],
         [-7, -7]],

        [[-6, -6],
         [-5, -5]]])
tensor([[[  9,  20],
         [ 30,  44]],

        [[ 55,  72],
         [ 84, 104]]])
tensor([[[0.1111, 0.2000],
         [0.3000, 0.3636]],

        [[0.4545, 0.5000],
         [0.5833, 0.6154]]])
tensor([[[ 29,  32],
         [ 67,  74]],

        [[127, 138],
         [173, 188]]])


In [18]:
print(tensor1.add_(tensor2)) # tensor1를 tensor2와의 합의 결과로 다시 저장
print(tensor1)
print(tensor1.subtract_(tensor2))

tensor([[[10, 12],
         [13, 15]],

        [[16, 18],
         [19, 21]]])
tensor([[[10, 12],
         [13, 15]],

        [[16, 18],
         [19, 21]]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


# **2. 파이토치와 텐서**

In [19]:
data = [[1, 2], [3, 4]]

data

[[1, 2], [3, 4]]

In [20]:
data_tensor = torch.tensor(data)

data_tensor

tensor([[1, 2],
        [3, 4]])

In [21]:
import numpy as np

In [22]:
ndarray = np.array(data_tensor)

ndarray

array([[1, 2],
       [3, 4]])

In [23]:
data_tensor = torch.tensor(ndarray)

data_tensor

tensor([[1, 2],
        [3, 4]])

In [24]:
a = torch.ones(2, 3)

a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [25]:
b = torch.zeros(3, 4)

b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
c = torch.full((3, 4), 7)

c

tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])

In [27]:
d = torch.empty(2, 3)

d

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])

In [28]:
e = torch.eye(5)

print(e)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [29]:
f = torch.arange(10)

f

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
g = torch.rand(2, 3)

g

tensor([[0.7545, 0.0076, 0.2740],
        [0.5417, 0.1085, 0.4720]])

In [31]:
h = torch.randn(2, 3) # 평균이 0이고 표준편차가 1인 정규 분포에서 무작위 샘플링

h

tensor([[-0.0270, -0.8440,  2.1611],
        [ 1.0811,  0.2429, -0.7450]])

In [32]:
i = torch.arange(16).reshape(2, 2, 4)

i, i.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7]],
 
         [[ 8,  9, 10, 11],
          [12, 13, 14, 15]]]),
 torch.Size([2, 2, 4]))

In [33]:
# permute() : 차원을 지정한 인덱스로 변환
# i.shape = ([2, 2, 4]) -> ([4, 2, 2])

j = i.permute((2, 1, 0)) # ([2, 2, 4]) 의 인덱스 순서를 permute 안에 입력한 순서로 변경

print(j)
print(j.shape)

tensor([[[ 0,  8],
         [ 4, 12]],

        [[ 1,  9],
         [ 5, 13]],

        [[ 2, 10],
         [ 6, 14]],

        [[ 3, 11],
         [ 7, 15]]])
torch.Size([4, 2, 2])


In [34]:
a = torch.arange(1, 13).reshape(3, 4)

a

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [35]:
a[1]

tensor([5, 6, 7, 8])

In [36]:
a[0, -1]

tensor(4)

In [37]:
print(a[1 : -1])

tensor([[5, 6, 7, 8]])


In [38]:
a[: 2, 2 :]

tensor([[3, 4],
        [7, 8]])

# **3.Colab 에서 GPU 사용하기**

* 코랩에서 device 변경하는 방법
    * 상단 메뉴 -> 런타임 -> 런타임 유형변경 -> 하드웨어 가속기를 GPU로 변경 -> 저장 -> 세션 다시 시작 및 모두 실행

In [39]:
tensor = torch.rand(3, 4)

print(tensor)
print(tensor.shape)
print(type(tensor))
print(tensor.dtype)
print(tensor.device)

tensor([[0.6356, 0.5091, 0.4067, 0.0411],
        [0.6641, 0.2496, 0.8456, 0.9792],
        [0.0147, 0.4700, 0.5969, 0.2226]])
torch.Size([3, 4])
<class 'torch.Tensor'>
torch.float32
cpu


In [40]:
# is_available() : gpu를 사용 할 수 있는지 여부

if torch.cuda.is_available() :
    print('GPU를 사용 할 수 있음')
    tensor = tensor.to('cuda')

print(tensor.device)

GPU를 사용 할 수 있음
cuda:0
