# **1. 넘파이(Numpy)**

* 파이썬에서 사용되는 과학 및 수학 연산을 위한 강력한 라이브러리
* 주로 다차원 배열을 다루는 데에 특화되어 있어, 데이터 분석, 머신러닝, 과학 계산 등 다양한 분야에서 널리 사용
* 넘파이 배열은 c 언어로 구현되어 있어 연산이 빠르고 효율적
* 넘파이 배열은큰 데이터셋에서 수치 연산을 수행할 때 뛰어난 성능을 보이며 메모리 사용을 최적화 시키고 효율적으로 관리

# **2. 넘파이의 주요 특징과 기능**

### 2-1. 다차원 배열 (N-dimensional array)

* 넘파이의 핵심은 다차원 배열 ndarray
* ndarray는 동일한 자료형을 가지는 원소들로 이루어져 있음

In [5]:
list1 = [1, 2, 3, 4]

print(list1)
print(type(list1))
print(type(list1[0]))

list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

print(list2)
print(type(list2))
print(type(list2[0]))

[1, 2, 3, 4]
<class 'list'>
<class 'int'>
[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
<class 'list'>


In [6]:
import numpy as np

In [11]:
ndarr1 = np.array([1, 2, 3, 4])

print(ndarr1)
print(type(ndarr1))
print(type(ndarr1[0]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [14]:
ndarr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(ndarr2)
print(type(ndarr2))
print(type(ndarr2[0]))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### 2-2. 리스트와 ndarray 변환

In [16]:
# 리스트를 ndarray로 변환

list1 = [1, 2, 3, 4]
ndarr1 = np.array(list1)

print(ndarr1)
print(type(ndarr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [18]:
# ndarray를 list로 변환

list2 = ndarr1.tolist()

print(list2)
print(type(list2))

[1, 2, 3, 4]
<class 'list'>


### 2-3. ndarray 의 데이터 타입
* 넘파이의 ndarray 는 동일한 자료형을 가지는 원소들로 이루어져 있으며 다양한 데이터 타입을 지원

In [23]:
list1 = [1, 3.1, 'python', True, '✔']

print(list1)
print(type(list1))
print(type(list1[0]))
print(type(list1[1]))
print(type(list1[2]))
print(type(list1[3]))
print(type(list1[4]))

[1, 3.1, 'python', True, '✔']
<class 'list'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'str'>


In [25]:
ndarr1 = np.array([1, 2, 3, 4])

print(ndarr1)
print(type(ndarr1))
print(type(ndarr1[0]))
print(type(ndarr1[1]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [30]:
ndarr2 = np.array([1, 2, 3.14, 5])

print(ndarr2)
print(type(ndarr2))
print(type(ndarr2[0]))

[1.   2.   3.14 5.  ]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [34]:
ndarr3 = np.array([1, 2, 3.14, True])

print(ndarr3)
print(type(ndarr3[0]))

[1.   2.   3.14 1.  ]
<class 'numpy.float64'>


In [36]:
ndarr4 = np.array(['1', 2, 3.14, True])

print(ndarr4)
print(type(ndarr4[2]))

['1' '2' '3.14' 'True']
<class 'numpy.str_'>


In [38]:
ndarr3 = np.array([1, 2, 3.14, True], dtype = int) # 모든 요소를 int형으로 변환

print(ndarr3)
print(type(ndarr3[0]))

[1 2 3 1]
<class 'numpy.int64'>


In [42]:
ndarr4 = np.array(['1', 2, 3.14, True], dtype = int)

print(ndarr4)
print(type(ndarr4[2]))

[1 2 3 1]
<class 'numpy.int64'>


### 2-4. ndarray의 인덱싱과 슬라이싱

In [45]:
arr1 = np.array(['🍇', '🍓', '🍎', '🍍', '🍌'])

print(arr1)
print(arr1.shape) # 차원

['🍇' '🍓' '🍎' '🍍' '🍌']
(5,)


In [48]:
#  인덱싱

print(arr1[0])
print(arr1[4])
print(arr1[-1])

🍇
🍌
🍌


In [55]:
# 슬라이싱

print(arr1[0 : 3])
print(arr1[2 : ])
print(arr1[ : 3])

['🍇' '🍓' '🍎']
['🍎' '🍍' '🍌']
['🍇' '🍓' '🍎']


In [58]:
# 2차원 배열

arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print(arr2d)
print(arr2d.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [60]:
# 0행 가져오기

print(arr2d[0, :])
print(arr2d[0, ])
print(arr2d[0])

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [62]:
# 0열 가져오기

print(arr2d[:, 0])


[1 5 9]


### 2-5. Fancy indexing

* 정수 배열이나 불리언 배열을 사용하여 배열의 일부를 선택하는 방법

* 여러개의 요소를 한번에 선택하거나 조건에 맞게 선택할 수 있음

In [67]:
arr1 = np.array([10, 15, 36, 2, 5, 44, 76, 93, 78, 39])

idx = [2, 5, 9]
arr1[idx]

array([36, 44, 39])

In [69]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 2-6. Boolean indexing

* 불리언 값으로 이루어진 배열을 사용하여 조건을 충족하는 원소만 선택하는 방법

In [73]:
arr1 = np.array([1, 2, 3, 4, 5])

sel = [True, False, True, True, False] # 인덱싱 하고자 하는 요소 개수와 일치해야 한다.
arr1[sel]

array([1, 3, 4])

In [77]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print(arr2d[arr2d > 7])
print(arr2d > 7)

[ 8  9 10 11 12]
[[False False False False]
 [False False False  True]
 [ True  True  True  True]]


# **3. 행열 연산**

* 넘파이에서는 다차원 배열인 ndarray를 사용하여 행열 연산을 수행
* 행열 연산은 선형 대수와 관련이 깊어 데이터 과학, 머신러닝,통계 등 다양한 분야에서 사용

In [83]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[3, 5, 6],
                 [1, 2, 3]])

print(arr1.shape)
print(arr2.shape)

(2, 3)
(2, 3)


In [82]:
# 행열 덧셈

arr1 + arr2

array([[4, 7, 9],
       [5, 7, 9]])

In [84]:
# 행열 뺄셈

arr1 - arr2

array([[-2, -3, -3],
       [ 3,  3,  3]])

In [85]:
# 행열 원소별 곱셈

arr1 * arr2

array([[ 3, 10, 18],
       [ 4, 10, 18]])

In [87]:
# 행열 나눗셈

arr1 / arr2

array([[0.33333333, 0.4       , 0.5       ],
       [4.        , 2.5       , 2.        ]])

In [90]:
# 행열곱(matrix multiplication)
# 행열곱의 조건 : 맞닿는 shape가 같아야함. 떨어져 있는 shape가 결과 행열이 됨
# (2, 3) @ (3, 2) -> (2, 2)
# 선형 변환을 표현하고 계산하는 도구로 사용(행열이 공간을 다른 공간으로 변환)
# 선형 연립 방정식을 행열 형태로 나타내고 이를 풀기 위해 행열 곱을 사용


arr3 = np.array([[1, 2, 3],
                 [2, 3, 4],
                 [1, 2, 3]])

arr4 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

print(arr3.shape)
print(arr4.shape)

(3, 3)
(3, 2)


In [92]:
print(arr3 @ arr4)

[[22 28]
 [31 40]
 [22 28]]


In [94]:
np.dot(arr3, arr4)

array([[22, 28],
       [31, 40],
       [22, 28]])

In [96]:
# 전치 행열
# 기존 행열의 행과 열을 바꾼 새로운 행열

print(arr1)
print(arr1.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [99]:
# 역행열
# 주어진 정사각 행열에 대한 곱셈 연산으로 단위 행열을 얻을 수 있는 행열
# 단위 행열: 주대각선의 원소가 모두 1이고 나머지 원소가 모두 0인 정사각형 행열

arr = np.array([[1, 2],
                [3, 4]])

print(np.linalg.inv(arr))
print(arr @ np.linalg.inv(arr))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# **4. 순차적인 값 생성**

In [101]:
arr1 = range(1, 11)

print(arr1)

for i in arr1 :
    print(i, end = ' ')

range(1, 11)
1 2 3 4 5 6 7 8 9 10 

In [108]:
# 반환되는 값은 ndarray 형태

arr2 = np.arange(1, 11)

print(arr2)
print(type(arr2))

for i in arr2 :
    print(i, end = ' ')

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
1 2 3 4 5 6 7 8 9 10 

# **5. 정렬**

In [110]:
arr1 = np.array([1, 2, 10, 5, 6, 9, 20, 1, 23, 35])

print(arr1)

[ 1  2 10  5  6  9 20  1 23 35]


In [114]:
print(np.sort(arr1)) # 오름차순

[ 1  1  2  5  6  9 10 20 23 35]


In [116]:
arr1 # inplace 연산이 되지 않음

array([ 1,  2, 10,  5,  6,  9, 20,  1, 23, 35])

In [118]:
np.sort(arr1)[::-1] # 내림차순

array([35, 23, 20, 10,  9,  6,  5,  2,  1,  1])

In [120]:
arr2d = np.array([[11, 1, 12, 9],
                  [3, 1, 4, 6],
                  [5, 6, 7, 8]])

print(arr2d.shape)

(3, 4)


In [122]:
np.sort(arr2d, axis = 0) # 행정렬

array([[ 3,  1,  4,  6],
       [ 5,  1,  7,  8],
       [11,  6, 12,  9]])

In [123]:
np.sort(arr2d, axis = 1) # 열정렬


array([[ 1,  9, 11, 12],
       [ 1,  3,  4,  6],
       [ 5,  6,  7,  8]])

In [124]:
np.sort(arr2d, axis = 1)[:, :: -1]

array([[12, 11,  9,  1],
       [ 6,  4,  3,  1],
       [ 8,  7,  6,  5]])

In [125]:
np.sort(arr2d, axis = -1) # 축의 마지막 방향

array([[ 1,  9, 11, 12],
       [ 1,  3,  4,  6],
       [ 5,  6,  7,  8]])